### ISSUE TITLE
Consider force-disabling autocorrect to speed up testing

### ISSUE THREAD

**Issue by geminoz** [chrisdukakis/hub#1]
How to reproduce:

- reach http://52.18.170.164:5000 (currently on Safari on the latest stable macOS)
- input `getcredit X` or `getbalance X`
- text is autocorrected to `get credit X` or `get balance X` due to autocorrect

Expected behaviour:

- text would be kept at `getcredit X` 

I completely understand this is all happening on the client side and that the autocorrection happening is in no way pushed by the test interface itself, however if possible I suggest to disable autocorrect via javascript to enable faster typing while testing.

Feel free to close and disregard if you don't see this ticket fit for purpose. 
Thanks,
GM

**Comment by chrisdukakis** [comment]
Thanks for this! Was good to report it! autocorrect="off" did the trick!
