### ISSUE TITLE
if address is reused, new deposit doesn't show in balance

### ISSUE THREAD

**Issue by project-Shift** [chrisdukakis/hub#2]
If the account holder forgets to issue a new deposit address and ends up reusing the same previous deposit address, getcredit does not show the second deposit balance
New deposits made with new addresses are correctly accounted for, regardless of the reused ones

**Comment by b3dk7** [comment]
I just tested this but it seems to work for me. Made two payments from wallet to hub using same deposit address and getcredit shows correct sum. Also tested the opposite i.e. two payments from hub to wallet and I can see both transactions.

**Comment by chrisdukakis** [comment]
Depositing on same address, multiple times works. It was not active on day 1 of testing.
