### ISSUE TITLE
Can't disable logs once enabled.

### ISSUE THREAD

**Issue by devender-yadav** [chrisdukakis/hub#6]
I am testing commands over http://52.18.170.164:5000/

Once I hit the command `logs`, logs are shown periodically even after entering further commands

    * [21:04:50] Status > Accounts: 126 | Deposits: 102 | Sweeps: 102 | Credits: 102 | Withdrawals: 164
    * [21:06:50] Status > Accounts: 126 | Deposits: 102 | Sweeps: 102 | Credits: 102 | Withdrawals: 164
    * [21:06:50] Status > Accounts: 126 | Deposits: 102 | Sweeps: 102 | Credits: 102 | Withdrawals: 164

Logs enable/disable option should be there.

-Dev

**Comment by b3dk7** [comment]
I am noticing the same behaviour

**Comment by chrisdukakis** [comment]
This is related to https://github.com/chrisdukakis/hub-tests which not hub itself. Not too important, it's just for testing.
